# Generated by Django 4.2 on 2023-11-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "aid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("pname", models.CharField(max_length=20)),
                ("pid", models.CharField(max_length=30)),
                ("pbirth", models.DateField()),
                ("psex", models.CharField(max_length=1)),
                ("pcountry", models.CharField(max_length=20)),
                ("balance", models.IntegerField()),
                ("regtime", models.DateField()),
                ("cert", models.CharField(max_length=50)),
                ("logpwdhash", models.CharField(max_length=32)),
                ("paypwdhash", models.CharField(max_length=32)),
            ],
        ),
    ]
