# Generated by Django 4.2 on 2023-11-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "cookie",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("uid", models.CharField(max_length=20)),
                ("live", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "rid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("orig_id", models.CharField(max_length=20)),
                ("recv_id", models.CharField(max_length=20)),
                ("money", models.IntegerField()),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(model_name="account", name="paypwdhash",),
        migrations.AlterField(
            model_name="account", name="regtime", field=models.DateTimeField(),
        ),
    ]
