# Generated by Django 4.2 on 2023-11-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_cookie_record_remove_account_paypwdhash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tel",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
