# Generated by Django 4.2 on 2023-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookie", name="live", field=models.CharField(max_length=20),
        ),
    ]
