# Generated by Django 4.2 on 2023-11-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_record_money"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="cert",),
        migrations.RemoveField(model_name="account", name="pcountry",),
    ]
